name: NASA
on:
  push:
      branches: [ main ]
      pull_request: 
        branches: [ main ]
jobs:
  build: 
    runs-on: ubuntu-lastest
    steps:
      - uses: action/checkout@v2
      - name: Use Node.js version 16
      uses: actions/steps-node@v2
      with: 
        node-version: '16'
      - run: npm install 
      - run: npm run build --prefix client 