name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js version 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
       - run : npm install 
       - run : npm run build --prefix client 
    - run: npm test