name: NASA Project CI
on:
  push:
      branches: [main]
      pull_request: 
          branches: [main]
jobs:
  build: 
    runs-on : window-lastest
    steps:
    - uses: actions/checkout@v4
    - name : Use Node.js version 16
      uses : action/steps-nodev2
      with: 
      node-version: '16'
    - run : npm install 
    - run : npm run build --prefix client 