name: NASA Project CI
on:
  push:
      branches: [master]
      pull_request: 
          branches: [master]
jobs:
  buidl: 
    runs-on: ubuntu  -lastest
      steps:
        - uses: action/checkout@v2
        - name: Use Node.js version 16
          uses: action/steps-node@v2
            with: 
            node-version: '16'
            - run: npm install 
            - run: npm run build --prefix client 